package com.livixa.apacam.client.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table NOTE.
 */
public class UserDao extends AbstractDao<UserTable, Long> {

	public static final String TABLENAME = "User";

	/**
	 * Properties of entity Note.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id",
				true, "_id");
		public final static Property USERNAME = new Property(1, String.class,
				"USERNAME", false, "USERNAME");
		public final static Property NAME = new Property(2, String.class,
				"Name", false, "Name");
		public final static Property EMAIL = new Property(3, String.class,
				"EMAIL", false, "EMAIL");
	}

	public UserDao(DaoConfig config) {
		super(config);
	}
//abc
	/*public UserDao(DaoConfig config, DaoSession daoSession) {
		super(config, daoSession);
	}*/

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'" + TABLENAME + "' (" + //
				"'_id' INTEGER PRIMARY KEY ," + // 0: id
				"'USERNAME' TEXT NOT NULL," + // 1: Slug
				"'Name' TEXT NOT NULL," + // 2: Name
				"'EMAIL' TEXT NOT NULL);" // 3: Rank
		);
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'"
				+ TABLENAME + "'";
		db.execSQL(sql);
	}

	@Override
	protected void bindValues(SQLiteStatement stmt, UserTable entity) {
		stmt.clearBindings();
		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}
//		stmt.bindString(2, entity.getUrl_slug());
//		stmt.bindString(3, entity.getName());
//		stmt.bindString(4, entity.getRank());
	}

	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public UserTable readEntity(Cursor cursor, int offset) {
		UserTable entity = new UserTable(
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.getString(offset + 1), cursor.getString(offset + 2),
				cursor.getString(offset + 3) // text
		);
		return entity;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public void readEntity(Cursor cursor, UserTable entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
//		entity.setUrl_slug(cursor.getString(offset + 1));
//		entity.setName(cursor.getString(offset + 2));
//		entity.setRank(cursor.getString(offset + 3));
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected Long updateKeyAfterInsert(UserTable entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Long getKey(UserTable entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

}
