package com.livixa.apacam.client.database;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table NOTE.
 */

public class UserRoomTable implements Serializable {

	/**
     *
     */
	private static final long serialVersionUID = 1L;
	private long id;
	private String userid;
	private String roomid;
	private String name;

	public UserRoomTable() {
	}

	public UserRoomTable(int id) {
		this.id = id;
	}

	public UserRoomTable(String userid, String roomid, String name) {
		this.userid = userid;
		this.roomid = roomid;
		this.name = name;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public String getRoomid() {
		return roomid;
	}

	public String getUserid() {
		return userid;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setRoomid(String roomid) {
		this.roomid = roomid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
