package com.livixa.apacam.client.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table NOTE.
 */

public class UserTable {

	private long id;
	private String userid;
	private String name;
	private String email;

	public UserTable() {
	}

	public UserTable(int id) {
		this.id = id;
	}

	public UserTable(long id, String userid, String name, String email) {
		this.id = id;
		this.userid = userid;
		this.name = name;
		this.email = email;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public String getUserid() {
		return userid;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
